version: '3.8'

services:
  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_URL=redis://redis:${REDIS_PORT}
    depends_on:
      - db
      - redis
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "16379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
